language: php
php:
  - 5.5.21
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 5.6
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - phpcs -p --extensions=php --standard=PSR2,PSR1 ./src ./tests

notifications:
  email: false
